import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html
        lang="en"
      >
        <body>
          <nav className="flex items-center justify-between p-4 text-blue-900 font-bold">
            <div className="logo font-bold flex items-center">
              <Image
                src="/logo1.png" // Path relative to the public folder
                alt="My Company Logo"
                width={100} // Adjust the width to fit your layout
                height={20} // Adjust the height to fit your layout
                priority // Add priority if this is the first image seen (like in a navbar)
              />
            </div>
            <div className="flex gap-4">
              <Link href="/">Home</Link>
              <Link href="/places">Places</Link>
            </div>
          </nav>
          {children}
        </body>
      </html>
    </>
  );
}

