import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";

export const metadata = {
  title: "Mini Tourist App",
  description: "Generated by developer",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html
        lang="en"
      >
        <body>
          <nav className="flex items-center justify-between p-4 text-blue-900 font-bold">
            <div className="logo font-bold flex items-center">
              <Image
                src="/logo1.png"
                alt="My Company Logo"
                width={100}
                height={20}
                priority
              />
            </div>
            <div className="flex gap-4">
              <Link href="/">Home</Link>
              <Link href="/places">Places</Link>
              <Link href="/add-place">Add-Place</Link>
              <Link href="/favorites">Favorites</Link>
            </div>
          </nav>
          {children}
        </body>
      </html>
    </>
  );
}

